### ISSUE TITLE
Changing Anonymous Username

### ISSUE THREAD

**Issue by KarlCraven** [steveurkel123/incognito#2]
Hey,

At https://www.phpbb.com/community/viewtopic.php?p=13953606#p13953606 you said:

> I've created a new version 0.9.1 meanwhile and added the feature to give a specific username for the anonymous posts. You can add this in the ACP.

Where do I find this option?

Thanks!

**Comment by steveurkel123** [comment]
Hi,

ideally you should find this in the Admin area of the extension. Please have a look at below screenshot.

![image](https://cloud.githubusercontent.com/assets/9503331/10117315/d9ac9c4e-6452-11e5-9c4e-35ccb81ab645.png)

**Comment by KarlCraven** [comment]
Thanks. I've only just upgraded to phpBB 3.1 so I am not used to the new extension system.
